### ISSUE TITLE
Return the length of the array/slice

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#135]
Write a function that returns the length of the array/slice. For example:

```golang
number := lengthArray(myArray)
```

- [ ] Implement the function as part of the `internal/utils` pkg
- [ ] Write unit test
- [ ] Make sure there are [testable examples](https://blog.golang.org/examples)
- [ ] For logging use https://github.com/Sirupsen/logrus
- [ ] in case of specific errors please store them separately to `internal/errors` pkg

**Hints**
* As an exercise, try to write the test first. Let it fail. Then try to fix it, by writing the actual implementation of the function.

Extra help
- https://gopher.gr/arrays-me-tin-golang/
- https://gopher.gr/basic-unit-testing-me-golang/
* For logging https://linuxhint.com/golang-logrus-package/

**Comment by zoispag** [comment]
`len` and `cap` are built-in methods. Not needed.
