### ISSUE TITLE
Verify a zip file

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#136]
Make sure a file is a valid Zip file

Example:
```go
err := isZip(filepath)
```

**Acceptance Criteria**
- [ ] Write a function as part of the `internal/utils` pkg
- [ ] Write a unit test
- [ ] Make sure there are [testable examples](https://blog.golang.org/examples)
- [ ] For specific error messages put them into `internal/errors` pkg
- [ ] Make the code part of `internal/zip` pkg
- [ ] For logging use https://github.com/Sirupsen/logrus

**Hints:**
- Do not create a real zip file on the filesystem. Use mocking.
- As an exercise, try to write the test first. Let it fail. Then try to fix it, by writing the actual implementation of the function.

**Extra help:**
- https://github.com/spf13/afero for testing
- For logging https://linuxhint.com/golang-logrus-package/

**NOTICE**: If you are unable to mock this test, in worst case scenario, create a folder `internal/zip/testdata` and put actual files you can use for your test.

**Comment by zoispag** [comment]
See Archive method of [go-unarr](https://github.com/gen2brain/go-unarr#open-archive).

**Comment by zoispag** [comment]
@drpaneas this is indirectly covered by #163. Do we still need it?
