### ISSUE TITLE
Extract the extension of a filepath

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#138]
Example:
```go
ext, err := getExtension(filepath) 
if err != nil {
  // log error
}
fmt.Println(ext)
```

**Acceptance Criteria**
- [ ] Make the function be part of the `internal/utils.go` pkg
- [ ] If the filepath doesn't exist, return an error
- [ ] Verify the extension doesn't contain any `.` dots
- [ ] For logging use https://github.com/Sirupsen/logrus
- [ ] Write a unit test
- [ ] Make sure there are [testable examples](https://blog.golang.org/examples)
- [ ] For specific errors, make the part of the `internal/errors` pkg as consts

**Hints**:
* You don't really need to check if the filepath exists
* As an exercise, try to write the test first. Let it fail. Then try to fix it, by writing the actual implementation of the function.
* For logging https://linuxhint.com/golang-logrus-package/

**Comment by zoispag** [comment]
Standard go "path/filepath" method: `extension := filepath.Ext(filepath)`.
Close this one?
