### ISSUE TITLE
Extract the filename of a filepath

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#139]
Example:
```go
ext, err := getFilename(filepath) 
if err != nil {
  log.Error(err)
}
fmt.Println(ext)
```

**Acceptance Criteria**
- [ ] Make the function be part of the `internal/utils.go` pkg
- [ ] If the filepath doesn't exist, return an error
- [ ] For logging use https://github.com/Sirupsen/logrus
- [ ] Verify the extension doesn't contain any `.` dots
- [ ] Write a unit test
- [ ] Make sure there are [testable examples](https://blog.golang.org/examples)
- [ ] For specific errors, make the part of the `internal/errors` pkg as consts

Hints:
* You don't need to check if the filepath truly exists.
* As an exercise, try to write the test first. Let it fail. Then try to fix it, by writing the actual implementation of the function.
* For logging https://linuxhint.com/golang-logrus-package/

**Comment by zoispag** [comment]
Built-in using either

- `filepath.Base()`
See [playground](https://play.golang.org/p/DzlCV-HC-r)

```go
path := "/some/path/to/remove/file.name"
file := filepath.Base(path)
fmt.Println(file)
// Output: file.name
```

- or `filepath.Split()`
See [playground](https://play.golang.org/p/G0kJUazYNH9)

```go
dir, file := filepath.Split("/some/path/to/remove/file.name")
fmt.Println(dir)
// Output: /some/path/to/remove/

fmt.Println(file)
// Output: file.name
```
