### ISSUE TITLE
Extract a zip archive

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#142]
**Dev story**
Write a function/method that extracts the contents of a zip archive

Example:
```go
err := unzip(filepath)
```

**Acceptance Criteria**
- [x] Use https://github.com/spf13/afero for filesystem abstraction
- [ ] Make sure it works cross-platform
- [x] Make sure the file exists before you try to unzip it and it's a valid zip file
- [x] Put the function into `internal/zip` package
- [x] For logging use https://github.com/Sirupsen/logrus
- [x] Write a unit test
- [ ] Use https://github.com/gen2brain/go-unarr 
- [ ] Make sure there are [testable examples](https://blog.golang.org/examples)

**Hints**:
* Writing a unit test for filesystem checking is not trivial. You should NOT create a real file on the system, because then your test will depend on the I/O of the file system itself. The last resort is mocking the filesystem. There are quite a few powerful libraries like spf13/afero for this purpose (mocking of a filesystem). These packages will create temporary files in the background and clean up afterward.
* As an exercise, try to write the test first. Let it fail. Then try to fix it, by writing the actual implementation of the function.

**Extra Help**:
* https://golangcode.com/check-if-a-file-exists/
* https://www.youtube.com/watch?v=ifBUfIb7kdo
* https://github.com/spf13/afero#using-afero-for-testing
* An example using Afero for testing: http://krsacme.com/golang-fs-tests/
* For logging https://linuxhint.com/golang-logrus-package/

**NOTICE**: If you are unable to mock this test, in worst case scenario, create a folder `internal/zip/testdata` and put actual files you can use for your test.

**Comment by zoispag** [comment]
I think we should use [gen2brain/go-unarr](https://github.com/gen2brain/go-unarr) for unarchiving. This package provides Go bindings for the unarr C package, which looks like a great candidate that can handle `.zip`, `.tar`, `.7z` & `.rar`.

The same applies for #143

@drpaneas ?

**Comment by drpaneas** [comment]
They @zoispag thanks for the link. I'd leave this up to the judgement of the person working on the ticket. If this library works with all of those standard/common compressions, then be my guest. I just updated the ticket accordingly. 👍

**Comment by zoispag** [comment]
> * Make sure there are [testable examples](https://blog.golang.org/examples)

@drpaneas that's kind of tricky. How do I make an example that requires a zip file to exist?

**Comment by zoispag** [comment]
I called the package `archive` rather than zip. It felt weird to have a method to extract a `7z` or a `rar` in a package called `zip`. :)
