### ISSUE TITLE
Delete file

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#145]
**Dev story**
Write a function/method that deletes a file (equiv to Linux command `rm`)

Example:
```go
err := rm(filepath)
```

**Acceptance Criteria**
- [x] Make sure it works cross-platform
- [x] Put the function into `internal/utils` package
- [x] For logging use https://github.com/Sirupsen/logrus
- [x] Write a unit test
- [x] Make sure there are [testable examples](https://blog.golang.org/examples)

**Hints**:
* Writing a unit test for filesystem checking is not trivial. You should NOT create a real file on the system, because then your test will depend on the I/O of the file system itself. The last resort is mocking the filesystem. There are quite a few powerful libraries like spf13/afero for this purpose (mocking of a filesystem). These packages will create temporary files in the background and clean up afterward.
* As an exercise, try to write the test first. Let it fail. Then try to fix it, by writing the actual implementation of the function.

**Extra Help**:
* https://golangcode.com/check-if-a-file-exists/
* https://www.youtube.com/watch?v=ifBUfIb7kdo
* https://github.com/spf13/afero#using-afero-for-testing
* An example using Afero for testing: http://krsacme.com/golang-fs-tests/
* For logging https://linuxhint.com/golang-logrus-package/

**NOTICE**: If you are unable to mock this test, in worst case scenario, create a folder `internal/utils/testdata` and put actual files you can use for your test.

**Comment by ge0r** [comment]
Should it also delete directories (since there is no `delete directory` issue) or is it file specific?

**Comment by zoispag** [comment]
> Should it also delete directories (since there is no `delete directory` issue) or is it file specific?

If we take this: `(equiv to Linux command rm)` literal, we shouldn't. But my instinct says that 1 method to delete files and dirs is enough.

**Comment by drpaneas** [comment]
Deleting specific files I guess it's alright, but deleting directories it's a bit scary. If the user has created files (for whatever random reason) inside of those directories, romie will delete them and they will lose them. I would prefer to not delete directories for now, but let's see in the future. We can always "enhance".
