### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#15]
#### Description

To make sure releases, checksums and signatures are reproducible, make some of the following modifications listed in https://goreleaser.com/customization/build/#reproducible-builds

#### Acceptance criteria

- [x] Read and implement [gorelease reproducible buils](https://goreleaser.com/customization/build/#reproducible-builds) configuration

Complexity: 1

**Comment by cerebrux** [comment]
Oh ! I see that I implemented (accidentally) the following :

"Modify mod_timestamp: by default this is empty string, set to {{.CommitTimestamp}} or a constant value instead."

So probably yes it fixes #15
