### ISSUE TITLE
chattr library doesn't work

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#183]
@ggkioulis you made a mistake into your `Remove` function (btw I renamed it into `RemoveFile`) while using the `chattr` library. This library[ DOES NOT create a file](https://play.golang.org/p/JKgd1IEfwVj). It assumes the file **pre-exists** and only then it modifies its attributes. If it cannot do it, then it throws an error e.g. in Windows it doesn't work:

```bash
$ go run main.go
2021/02/07 15:35:23 Cannot create immutable file chattr +i failed: Usage: chattr [-RVfhv] [+-=mode]... [file]...
Try 'chattr --help' for more information
. Err: exit status 1
exit status 1
```

but it Linux works fine: https://play.golang.com/p/hmDjGdoInBB

In your testing you are assuming the library is creating an immutable file -- which never happens. The fun part is that it doesn't through an error (lol) if you pass an non-existing file into it -- that's why you didn't discover it. Please don't use this library and re-write your tests accordingly without taking it into account. You can use `os.Chmod` if you like instead.

**Comment by ge0r** [comment]
> @ggkioulis you made a mistake into your `Remove` function (btw I renamed it into `RemoveFile`) while using the `chattr` library. This library[ DOES NOT create a file](https://play.golang.org/p/JKgd1IEfwVj). It assumes the file **pre-exists** and only then it modifies its attributes. If it cannot do it, then it throws an error e.g. in Windows it doesn't work:
> 
> ```shell
> $ go run main.go
> 2021/02/07 15:35:23 Cannot create immutable file chattr +i failed: Usage: chattr [-RVfhv] [+-=mode]... [file]...
> Try 'chattr --help' for more information
> . Err: exit status 1
> exit status 1
> ```
> 
> but it Linux works fine: https://play.golang.com/p/hmDjGdoInBB
> 
> In your testing you are assuming the library is creating an immutable file -- which never happens. The fun part is that it doesn't through an error (lol) if you pass an non-existing file into it -- that's why you didn't discover it. Please don't use this library and re-write your tests accordingly without taking it into account. You can use `os.Chmod` if you like instead.

I m a bit confused. In the test I assume that the library is only changing the file attributes.
I use `createFile(fileToDelete)` which creates the file and only then do I change it's attributes.
The reason that I do not use `os.Chmod` is that it did not work in windows, while `chattr` presumably did.

Do you mean that my `createFile(fileToDelete)` was not able to create a file in windows?

**Comment by ge0r** [comment]
I see what you mean now, my bad. I never created a `fileNotToDelete`!
