### ISSUE TITLE
Bot checks for conventional commits

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#22]
#### Description

It is essential we all have the same guideline/principle for pushing commit messages. Having a bot to ensure that will slow down the speed of an unorganised team and it will speed up the organised one.

#### Acceptance Criteria

- [x] Read and understand https://www.conventionalcommits.org/en/v1.0.0/
- [x] Now create and configure this [Semantic probot](https://github.com/zeke/semantic-pull-requests) for the repo 

Complexity: 2

**Comment by zoispag** [comment]
I personally enjoy using [gitmoji](https://gitmoji.carloscuesta.me/).
It also integrates nicely with [VSCode](https://marketplace.visualstudio.com/items?itemName=Vtrois.gitmoji-vscode).

WDYT?
