### ISSUE TITLE
Bot for auto merging

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#23]
#### Description

We need a bot that will either block or allow merging based on some conditions. In some rare cases, the bot will automatically merge PRs created by bots.

#### Acceptance Criteria

- [x] Install and read about [kodiak](https://github.com/chdsbd/kodiak) bot
- [x] Look for similar configuration in Github and post them here
- [ ] Configure it to merge only if there are 2 reviews and CI is green
- [ ] Configure it to automerge PRs coming from the CI that is updating the Go version and these two: `go.mod` and `go.sum`

** Alternative**: There is also [Mergify](https://github.com/marketplace/mergify) that is worth checking.

** Alternative 2**: Specifically for automerging there is also this GH Action: https://github.com/marketplace/actions/merge-pull-requests

Please provide review all of those ways, compare them and provide your feedbacks (cons/pros) and your experience.

**Comment by zoispag** [comment]
I personally use [probot-auto-merge](https://github.com/bobvanderlinden/probot-auto-merge) in a private GH repo. I would like to give both Mergify and kodiak a try. Ideally with this order. **Mergify** looks promising and I haven't had the change to use it in an OSS project yet.

**Comment by drpaneas** [comment]
> I would like to give both Mergify and kodiak a try. Ideally with this order. **Mergify** looks promising and I haven't had the change to use it in an OSS project yet.

Sure, go ahead ;)

**Comment by zoispag** [comment]
Relevant PRs #72 & #73
