### ISSUE TITLE
Block merging on WIP

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#26]
#### Description

When a PR is not ready, developers signal these by putting `WIP` in the commit message, so nobody is reviewing.

#### Acceptance Criteria

- [x] To ensure that this is not going to get merged by accident or we forget to remove the `WIP` from the title, use this https://github.com/marketplace/wip
- [x] Test it to verify

Complexity: 1

**Comment by cerebrux** [comment]
You should assign this to your self @drpaneas . The https://github.com/marketplace/wip needs to connect "billing info" with your account even if it has a free plan.

**Comment by drpaneas** [comment]
I tested it with the PR

```
WIP In progress — Title contains "wip"
```

work's done here 👍
