### ISSUE TITLE
Create a goreportcard

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#27]
#### Description

It's good to get a report for our code via a public service like goreport. Make sure it's visible on the front page, by adding the badge to the README

#### Acceptance Criteria

- [x] Create a card https://goreportcard.com/
- [x] Update README to reflect this as a badge

e.g. 

```html
<a href="https://goreportcard.com/report/github.com/drpaneas/romie">
      <img alt="Go Report Card" src="https://goreportcard.com/badge/github.com/drpaneas/romie?style=flat-square">
```

**Comment by ktsamis** [comment]
Since there is no README.md yet I combine the cards and do them both at the same time.
