### ISSUE TITLE
Mention contributors

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#30]
#### Description

There are many ways to highlight your contributors. One of those is via the readme. There are plenty of ways to do it. Check other github repos do get inspired.

#### Acceptance Criteria

- [ ] README highlights our contributors
- [ ] If there is a new contributor is should be added automatically to that.

**Comment by drpaneas** [comment]
use the all contributors bot

**Comment by ktsamis** [comment]
[Example](https://github.com/ktsamis/romie) of result of [all-contributors-bot](https://allcontributors.org/). Basically with a comment we can add contributors, it opens a new PR with the person's profile etc, you can see [an example PR here](https://github.com/ktsamis/romie/commit/da773d8a70d048e46af9f28e40d9238b3c4096b1) and [the initial PR for the first one here](https://github.com/ktsamis/romie/commit/6acbd60134c8ae2f3c84287a45c419e9d2ef6c6c). The only thing we need to do is install the [all-contributors-bot](https://allcontributors.org/) and then in a PR that we have open start mentioning all the people that have contributed for [each reason](https://allcontributors.org/docs/en/emoji-key). Let's talk about what we want to have as types in the [table configuration](https://allcontributors.org/docs/en/bot/configuration)

**Comment by ktsamis** [comment]
I think the [defaults](https://allcontributors.org/docs/en/emoji-key#table) are enough, I would like to use it a few times to see if the links are what we need for code, tests etc. I see [the code](https://github.com/ktsamis/romie/commit/da773d8a70d048e46af9f28e40d9238b3c4096b1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R25) is at least. @drpaneas what do you think?

**Comment by ktsamis** [comment]
Also [the current file](https://github.com/drpaneas/romie/blob/master/AUTHORS) will need to be removed, the Contributors will be added to the README

**Comment by drpaneas** [comment]
> you can see [an example PR here](https://github.com/ktsamis/romie/commit/da773d8a70d048e46af9f28e40d9238b3c4096b1) and [the initial PR for the first one here](https://github.com/ktsamis/romie/commit/6acbd60134c8ae2f3c84287a45c419e9d2ef6c6c).

Great work! Thanks for the verification :)

> The only thing we need to do is install the [all-contributors-bot](https://allcontributors.org/)

Already done.

> and then in a PR that we have open start mentioning all the people that have contributed for [each reason](https://allcontributors.org/docs/en/emoji-key). Let's talk about what we want to have as types in the [table configuration](https://allcontributors.org/docs/en/bot/configuration)

Please prepare the PR ;) No need to discuss the types, put whatever you see fit based on your judgement.

> Also [the current file](https://github.com/drpaneas/romie/blob/master/AUTHORS) will need to be removed, the Contributors will be added to the README

Need? The `AUTHORS` file is considered as a best practice for GH repos. In that file we will add the whole team (internal). This card is just for enhancing the exposure of our contributors (external people).

**Comment by ktsamis** [comment]
I will leave the defaults, I think they are good enough for us now. If we need more in the future we can add it. Basically from now if we want to add contributors a comment will be enough
