### ISSUE TITLE
PR author gets auto-assigned

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#35]
#### Description

In most cases, pull request author should be assigned an assignee of the pull request. This task makes sure the PR author assigns as an assignee.

#### Acceptance Criteria

- [ ] Install https://github.com/marketplace/actions/auto-author-assign
- [ ] Test it

Complexity: 2

**Comment by ktsamis** [comment]
Doesn't work, see https://github.com/drpaneas/romie/pull/54

**Comment by drpaneas** [comment]
Just sent a new PR, please review @ktsamis  @JohnGavr
