### ISSUE TITLE
Install RetroArch

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#41]
#### Description

It's essential to test based on the directory structure of the original retropie. Try to install it on the Linux Ubuntu 20.04 system in the CI. If it fails, at least re-create the structure where the roms go.

** Important**: This has to be implemented after https://github.com/drpaneas/romie/issues/40 is completed

#### Acceptance Criteria

- [x] Install RetroArch

**Comment by ktsamis** [comment]
if it helps https://www.retroarch.com/index.php?page=linux-instructions

**Comment by ge0r** [comment]
> if it helps https://www.retroarch.com/index.php?page=linux-instructions

Thanks Kosta!
The snap way allows to install cores straight from retroarch, however config is in `~/snap/retroarch/$number/.config/retroarch` so ubuntu repository it is.
