### ISSUE TITLE
Should we enforce good commits with GH Action?

### ISSUE THREAD

**Issue by cerebrux** [romie-gr/romie#44]
After reading : https://chris.beams.io/posts/git-commit/
I've found a github action workflow https://github.com/mristin/opinionated-commit-message that helps implementing the rules of a good commit message.

**Comment by drpaneas** [comment]
The second most important task for the upcoming sprint is https://github.com/drpaneas/romie/issues/22 which covers that issue.

**Comment by cerebrux** [comment]
Ok should we close this as duplicate ?
