### ISSUE TITLE
Check if connection is established

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#96]
Write a function checking if a connection returns HTTP 200 for a given URL.
In case of error, print the error message accordingly.

Example:
```go
err, hostOK := isOnline(URL url) {
if err != nil {
  log.Error(err)
}
if hostOK {
  // do something
}
```

**Acceptance Criteria**
- [ ] Use https://golang.org/pkg/net/url/
- [ ] Write the function as part of the `internal/utils` pkg
- [ ] For logging use https://github.com/Sirupsen/logrus
- [ ] Write unit-tests
- [ ] Make sure there are [testable examples](https://blog.golang.org/examples)
* in case of specific errors please store them separately to `internal/errors` pkg

**Hints**:
* During testing we don't want to communicate with a real webserver out there. Please mock.
* As an exercise, try to write the test first. Let it fail. Then try to fix it, by writing the actual implementation of the function.

Extra Help:
* https://gopher.gr/basic-unit-testing-me-golang/
* https://golang.org/src/net/http/httptest/example_test.go
* For logging https://linuxhint.com/golang-logrus-package/

**Comment by zoispag** [comment]
Note: We should follow redirects. Example:
- http://google.com -> 301 to https://google.com -> 200
